//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlimeNull.DuckovCoreUtilities.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlimeNull.DuckovCoreUtilities.Localization.SettingsText", typeof(SettingsText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity while aiming.
        /// </summary>
        internal static string AimOpacity {
            get {
                return ResourceManager.GetString("AimOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gain {0}.
        /// </summary>
        internal static string BlackMarketDemandGain {
            get {
                return ResourceManager.GetString("BlackMarketDemandGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lose {0}.
        /// </summary>
        internal static string BlackMarketDemandLoss {
            get {
                return ResourceManager.GetString("BlackMarketDemandLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to same.
        /// </summary>
        internal static string BlackMarketSame {
            get {
                return ResourceManager.GetString("BlackMarketSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same price.
        /// </summary>
        internal static string BlackMarketSamePrice {
            get {
                return ResourceManager.GetString("BlackMarketSamePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to costs {0} more.
        /// </summary>
        internal static string BlackMarketSupplyMore {
            get {
                return ResourceManager.GetString("BlackMarketSupplyMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save {0}.
        /// </summary>
        internal static string BlackMarketSupplySave {
            get {
                return ResourceManager.GetString("BlackMarketSupplySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / Total (x{1}): {2}.
        /// </summary>
        internal static string BlackMarketTotalFormat {
            get {
                return ResourceManager.GetString("BlackMarketTotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse period.
        /// </summary>
        internal static string BreathingPeriod {
            get {
                return ResourceManager.GetString("BreathingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds required for one outline brightness cycle.
        /// </summary>
        internal static string BreathingPeriodTooltip {
            get {
                return ResourceManager.GetString("BreathingPeriodTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close when hurt.
        /// </summary>
        internal static string CloseWhenHurt {
            get {
                return ResourceManager.GetString("CloseWhenHurt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close while moving.
        /// </summary>
        internal static string CloseWhileMoving {
            get {
                return ResourceManager.GetString("CloseWhileMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand price comparison baseline.
        /// </summary>
        internal static string DemandPriceBaseline {
            get {
                return ResourceManager.GetString("DemandPriceBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display duration.
        /// </summary>
        internal static string DisplayDuration {
            get {
                return ResourceManager.GetString("DisplayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display style.
        /// </summary>
        internal static string DisplayMode {
            get {
                return ResourceManager.GetString("DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display size.
        /// </summary>
        internal static string DisplaySize {
            get {
                return ResourceManager.GetString("DisplaySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade duration.
        /// </summary>
        internal static string FadeDuration {
            get {
                return ResourceManager.GetString("FadeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-close inventory.
        /// </summary>
        internal static string FeatureAutoCloseBackpack {
            get {
                return ResourceManager.GetString("FeatureAutoCloseBackpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black market price comparison.
        /// </summary>
        internal static string FeatureBlackMarketPrice {
            get {
                return ResourceManager.GetString("FeatureBlackMarketPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show BOSS locations.
        /// </summary>
        internal static string FeatureBossMapMarker {
            get {
                return ResourceManager.GetString("FeatureBossMapMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo crosshair color.
        /// </summary>
        internal static string FeatureCrosshairColor {
            get {
                return ResourceManager.GetString("FeatureCrosshairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show item prices.
        /// </summary>
        internal static string FeatureDisplayPrice {
            get {
                return ResourceManager.GetString("FeatureDisplayPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show item quality.
        /// </summary>
        internal static string FeatureDisplayQuality {
            get {
                return ResourceManager.GetString("FeatureDisplayQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade HUD while aiming.
        /// </summary>
        internal static string FeatureFadeHud {
            get {
                return ResourceManager.GetString("FeatureFadeHud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory sort buttons.
        /// </summary>
        internal static string FeatureInventorySort {
            get {
                return ResourceManager.GetString("FeatureInventorySort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show item uses.
        /// </summary>
        internal static string FeatureItemUsage {
            get {
                return ResourceManager.GetString("FeatureItemUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill feed.
        /// </summary>
        internal static string FeatureKillRecord {
            get {
                return ResourceManager.GetString("FeatureKillRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot outlines.
        /// </summary>
        internal static string FeatureLootOutline {
            get {
                return ResourceManager.GetString("FeatureLootOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low-health screen shadow.
        /// </summary>
        internal static string FeatureLowHealthShadow {
            get {
                return ResourceManager.GetString("FeatureLowHealthShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimap.
        /// </summary>
        internal static string FeatureMinimap {
            get {
                return ResourceManager.GetString("FeatureMinimap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick sleep.
        /// </summary>
        internal static string FeatureQuickSleep {
            get {
                return ResourceManager.GetString("FeatureQuickSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show inventory counts.
        /// </summary>
        internal static string FeatureStorageCount {
            get {
                return ResourceManager.GetString("FeatureStorageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When game loses focus.
        /// </summary>
        internal static string FeatureUnfocused {
            get {
                return ResourceManager.GetString("FeatureUnfocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty magazine color.
        /// </summary>
        internal static string FinalWarningColor {
            get {
                return ResourceManager.GetString("FinalWarningColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosshair color when the magazine is empty.
        /// </summary>
        internal static string FinalWarningColorTooltip {
            get {
                return ResourceManager.GetString("FinalWarningColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground item pulse.
        /// </summary>
        internal static string GroundItemBreathing {
            get {
                return ResourceManager.GetString("GroundItemBreathing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial warning color.
        /// </summary>
        internal static string InitialWarningColor {
            get {
                return ResourceManager.GetString("InitialWarningColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosshair color when first entering the low-ammo range.
        /// </summary>
        internal static string InitialWarningColorTooltip {
            get {
                return ResourceManager.GetString("InitialWarningColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item base price.
        /// </summary>
        internal static string ItemBasePrice {
            get {
                return ResourceManager.GetString("ItemBasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses.
        /// </summary>
        internal static string ItemUsageAvailable {
            get {
                return ResourceManager.GetString("ItemUsageAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed {0}.
        /// </summary>
        internal static string KillRecordDefaultFormat {
            get {
                return ResourceManager.GetString("KillRecordDefaultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot container pulse.
        /// </summary>
        internal static string LootboxBreathing {
            get {
                return ResourceManager.GetString("LootboxBreathing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed angle.
        /// </summary>
        internal static string MapFixedAngle {
            get {
                return ResourceManager.GetString("MapFixedAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow player rotation.
        /// </summary>
        internal static string MapFollowPlayer {
            get {
                return ResourceManager.GetString("MapFollowPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map orientation.
        /// </summary>
        internal static string MapOrientation {
            get {
                return ResourceManager.GetString("MapOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker color.
        /// </summary>
        internal static string MarkerColor {
            get {
                return ResourceManager.GetString("MarkerColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full effect below.
        /// </summary>
        internal static string MaximumEffectThreshold {
            get {
                return ResourceManager.GetString("MaximumEffectThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum entries.
        /// </summary>
        internal static string MaximumEntries {
            get {
                return ResourceManager.GetString("MaximumEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant buyback price.
        /// </summary>
        internal static string MerchantSellback {
            get {
                return ResourceManager.GetString("MerchantSellback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum opacity.
        /// </summary>
        internal static string MinimumOpacity {
            get {
                return ResourceManager.GetString("MinimumOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute while unfocused.
        /// </summary>
        internal static string MuteWhenUnfocused {
            get {
                return ResourceManager.GetString("MuteWhenUnfocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause while unfocused.
        /// </summary>
        internal static string PauseWhenUnfocused {
            get {
                return ResourceManager.GetString("PauseWhenUnfocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position mode.
        /// </summary>
        internal static string PositionMode {
            get {
                return ResourceManager.GetString("PositionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset time button 1.
        /// </summary>
        internal static string PresetTime1 {
            get {
                return ResourceManager.GetString("PresetTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset time button 2.
        /// </summary>
        internal static string PresetTime2 {
            get {
                return ResourceManager.GetString("PresetTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base price.
        /// </summary>
        internal static string PriceBase {
            get {
                return ResourceManager.GetString("PriceBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell price.
        /// </summary>
        internal static string PriceSell {
            get {
                return ResourceManager.GetString("PriceSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price type.
        /// </summary>
        internal static string PriceType {
            get {
                return ResourceManager.GetString("PriceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string QualityBackground {
            get {
                return ResourceManager.GetString("QualityBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        internal static string QualityBorder {
            get {
                return ResourceManager.GetString("QualityBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner badge.
        /// </summary>
        internal static string QualityCornerBadge {
            get {
                return ResourceManager.GetString("QualityCornerBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ESC to cancel.
        /// </summary>
        internal static string QuickSleepCancelHint {
            get {
                return ResourceManager.GetString("QuickSleepCancelHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled searching for a rainy day.
        /// </summary>
        internal static string QuickSleepCancelled {
            get {
                return ResourceManager.GetString("QuickSleepCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rainy day found after {0} day(s).
        /// </summary>
        internal static string QuickSleepExhausted {
            get {
                return ResourceManager.GetString("QuickSleepExhausted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is finally raining after {0} day(s)!.
        /// </summary>
        internal static string QuickSleepFound {
            get {
                return ResourceManager.GetString("QuickSleepFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storm End.
        /// </summary>
        internal static string QuickSleepStormEnd {
            get {
                return ResourceManager.GetString("QuickSleepStormEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Storm I.
        /// </summary>
        internal static string QuickSleepToStormI {
            get {
                return ResourceManager.GetString("QuickSleepToStormI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Storm II.
        /// </summary>
        internal static string QuickSleepToStormII {
            get {
                return ResourceManager.GetString("QuickSleepToStormII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To {0}.
        /// </summary>
        internal static string QuickSleepToTime {
            get {
                return ResourceManager.GetString("QuickSleepToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until Rainy.
        /// </summary>
        internal static string QuickSleepUntilRainy {
            get {
                return ResourceManager.GetString("QuickSleepUntilRainy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow color.
        /// </summary>
        internal static string ShadowColor {
            get {
                return ResourceManager.GetString("ShadowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow width.
        /// </summary>
        internal static string ShadowWidth {
            get {
                return ResourceManager.GetString("ShadowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show backpack count.
        /// </summary>
        internal static string ShowBackpackCount {
            get {
                return ResourceManager.GetString("ShowBackpackCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline ground items.
        /// </summary>
        internal static string ShowGroundItemOutline {
            get {
                return ResourceManager.GetString("ShowGroundItemOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline loot containers.
        /// </summary>
        internal static string ShowLootboxOutline {
            get {
                return ResourceManager.GetString("ShowLootboxOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show names.
        /// </summary>
        internal static string ShowNames {
            get {
                return ResourceManager.GetString("ShowNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show storage count.
        /// </summary>
        internal static string ShowRepositoryCount {
            get {
                return ResourceManager.GetString("ShowRepositoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start showing below.
        /// </summary>
        internal static string ShowThreshold {
            get {
                return ResourceManager.GetString("ShowThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carry.
        /// </summary>
        internal static string StorageCarry {
            get {
                return ResourceManager.GetString("StorageCarry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repo.
        /// </summary>
        internal static string StorageRepository {
            get {
                return ResourceManager.GetString("StorageRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text format.
        /// </summary>
        internal static string TextFormat {
            get {
                return ResourceManager.GetString("TextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is replaced with the target name.
        /// </summary>
        internal static string TextFormatTooltip {
            get {
                return ResourceManager.GetString("TextFormatTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic.
        /// </summary>
        internal static string TrackingDynamic {
            get {
                return ResourceManager.GetString("TrackingDynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        internal static string TrackingStatic {
            get {
                return ResourceManager.GetString("TrackingStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use item quality colors.
        /// </summary>
        internal static string UseQualityColor {
            get {
                return ResourceManager.GetString("UseQualityColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning threshold.
        /// </summary>
        internal static string WarningThreshold {
            get {
                return ResourceManager.GetString("WarningThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start changing the crosshair color below this remaining magazine ratio.
        /// </summary>
        internal static string WarningThresholdTooltip {
            get {
                return ResourceManager.GetString("WarningThresholdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in key.
        /// </summary>
        internal static string ZoomInKey {
            get {
                return ResourceManager.GetString("ZoomInKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out key.
        /// </summary>
        internal static string ZoomOutKey {
            get {
                return ResourceManager.GetString("ZoomOutKey", resourceCulture);
            }
        }
    }
}
