<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>SlimeNull.DuckovInterop.Bridge.Abstractions</AssemblyName>
    <RootNamespace>SlimeNull.DuckovInterop.Bridge</RootNamespace>
  </PropertyGroup>
</Project>
