//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlimeNull.DuckovModSettings.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlimeNull.DuckovModSettings.Localization.SettingsText", typeof(SettingsText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading... {0}/{1}.
        /// </summary>
        internal static string LoadingProgress {
            get {
                return ResourceManager.GetString("LoadingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Settings.
        /// </summary>
        internal static string ModSettings {
            get {
                return ResourceManager.GetString("ModSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No editable mod settings found.
        /// </summary>
        internal static string NoEditableModSettings {
            get {
                return ResourceManager.GetString("NoEditableModSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No editable settings found.
        /// </summary>
        internal static string NoEditableSettings {
            get {
                return ResourceManager.GetString("NoEditableSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching settings.
        /// </summary>
        internal static string NoMatchingSettings {
            get {
                return ResourceManager.GetString("NoMatchingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore defaults.
        /// </summary>
        internal static string RestoreDefaults {
            get {
                return ResourceManager.GetString("RestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search settings.
        /// </summary>
        internal static string SearchSettings {
            get {
                return ResourceManager.GetString("SearchSettings", resourceCulture);
            }
        }
    }
}
