<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Global.props" />

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>SlimeNull.DuckovCustomDeath</AssemblyName>
    <RootNamespace>SlimeNull.DuckovCustomDeath</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\Localization\ModLanguage.cs" Link="Localization\ModLanguage.cs" />
    <EmbeddedResource Update="Localization\SettingsText.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SettingsText.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Localization\SettingsText.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SettingsText.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ManagedPath)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TeamSoda.Duckov.Core">
      <HintPath>$(ManagedPath)\TeamSoda.Duckov.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TeamSoda.Duckov.Utilities">
      <HintPath>$(ManagedPath)\TeamSoda.Duckov.Utilities.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ItemStatsSystem">
      <HintPath>$(ManagedPath)\ItemStatsSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SodaLocalization">
      <HintPath>$(ManagedPath)\SodaLocalization.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ManagedPath)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ManagedPath)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="preview.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="info.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
