<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <LangVersion>12</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SlimeNull.DuckovCoreUtilities.HierarchyInspectorBridge</AssemblyName>
    <RootNamespace>SlimeNull.DuckovCoreUtilities.HierarchyInspectorBridge</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.Core" Version="1.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DuckovCoreUtilities.HierarchyInspector.Abstractions\DuckovCoreUtilities.HierarchyInspector.Abstractions.csproj" />
    <ProjectReference Include="..\JsonRpc\JsonRpc.csproj" />
  </ItemGroup>
</Project>
