<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>SlimeNull.DuckovCoreUtilities</AssemblyName>
    <RootNamespace>SlimeNull.DuckovCoreUtilities</RootNamespace>
    <DuckovPath>D:\Program Files (x86)\Steam\steamapps\common\Escape from Duckov</DuckovPath>
    <ManagedPath>$(DuckovPath)\Duckov_Data\Managed</ManagedPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ManagedPath)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TeamSoda.Duckov.Core">
      <HintPath>$(ManagedPath)\TeamSoda.Duckov.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TeamSoda.Duckov.Utilities">
      <HintPath>$(ManagedPath)\TeamSoda.Duckov.Utilities.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ItemStatsSystem">
      <HintPath>$(ManagedPath)\ItemStatsSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SodaLocalization">
      <HintPath>$(ManagedPath)\SodaLocalization.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ECM2">
      <HintPath>$(ManagedPath)\ECM2.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Plugins">
      <HintPath>$(ManagedPath)\Plugins.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Cinemachine">
      <HintPath>$(ManagedPath)\Cinemachine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>$(ManagedPath)\UniTask.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ManagedPath)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ManagedPath)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(ManagedPath)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(ManagedPath)\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(ManagedPath)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(ManagedPath)\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>$(ManagedPath)\UnityEngine.ParticleSystemModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(ManagedPath)\Unity.InputSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(ManagedPath)\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="EPO">
      <HintPath>$(ManagedPath)\EPO.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="info.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
