//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlimeNull.DuckovInterop.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlimeNull.DuckovInterop.Localization.SettingsText", typeof(SettingsText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic logging.
        /// </summary>
        internal static string DiagnosticLogging {
            get {
                return ResourceManager.GetString("DiagnosticLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write RPC requests and errors to the game log.
        /// </summary>
        internal static string DiagnosticLoggingTooltip {
            get {
                return ResourceManager.GetString("DiagnosticLoggingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen address.
        /// </summary>
        internal static string ListenAddress {
            get {
                return ResourceManager.GetString("ListenAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen port.
        /// </summary>
        internal static string ListenPort {
            get {
                return ResourceManager.GetString("ListenPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied when the service is re-enabled.
        /// </summary>
        internal static string RestartServiceTooltip {
            get {
                return ResourceManager.GetString("RestartServiceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable service.
        /// </summary>
        internal static string ServerEnabled {
            get {
                return ResourceManager.GetString("ServerEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the JSON RPC service used by the hierarchy inspector.
        /// </summary>
        internal static string ServerEnabledTooltip {
            get {
                return ResourceManager.GetString("ServerEnabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON RPC service.
        /// </summary>
        internal static string ServerGroup {
            get {
                return ResourceManager.GetString("ServerGroup", resourceCulture);
            }
        }
    }
}
