//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlimeNull.DockovParty.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlimeNull.DockovParty.Localization.SettingsText", typeof(SettingsText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}&apos;s game.
        /// </summary>
        internal static string ConnectedToGameFormat {
            get {
                return ResourceManager.GetString("ConnectedToGameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed..
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timed out..
        /// </summary>
        internal static string ConnectionTimedOut {
            get {
                return ResourceManager.GetString("ConnectionTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This container is being used by another player.
        /// </summary>
        internal static string ContainerInUse {
            get {
                return ResourceManager.GetString("ContainerInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The container lease has ended.
        /// </summary>
        internal static string ContainerLeaseEnded {
            get {
                return ResourceManager.GetString("ContainerLeaseEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host has not finished loading this container.
        /// </summary>
        internal static string ContainerNotLoaded {
            get {
                return ResourceManager.GetString("ContainerNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open this container.
        /// </summary>
        internal static string ContainerOpenFailed {
            get {
                return ResourceManager.GetString("ContainerOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another container is being synchronized.
        /// </summary>
        internal static string ContainerSyncInProgress {
            get {
                return ResourceManager.GetString("ContainerSyncInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The container version has changed.
        /// </summary>
        internal static string ContainerVersionUpdated {
            get {
                return ResourceManager.GetString("ContainerVersionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string DefaultPlayerName {
            get {
                return ResourceManager.GetString("DefaultPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected destinations do not match.
        /// </summary>
        internal static string DestinationMismatchLocal {
            get {
                return ResourceManager.GetString("DestinationMismatchLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected different destinations. Choose the same scene..
        /// </summary>
        internal static string DestinationMismatchRemote {
            get {
                return ResourceManager.GetString("DestinationMismatchRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic logging.
        /// </summary>
        internal static string DiagnosticLogging {
            get {
                return ResourceManager.GetString("DiagnosticLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write multiplayer protocol traffic to the game log.
        /// </summary>
        internal static string DiagnosticLoggingTooltip {
            get {
                return ResourceManager.GetString("DiagnosticLoggingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game version mismatch (host {0}, client {1})..
        /// </summary>
        internal static string GameVersionMismatch {
            get {
                return ResourceManager.GetString("GameVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item has been picked up.
        /// </summary>
        internal static string GroundItemTaken {
            get {
                return ResourceManager.GetString("GroundItemTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was picked up by another player.
        /// </summary>
        internal static string GroundItemTakenByOther {
            get {
                return ResourceManager.GetString("GroundItemTakenByOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from the host.
        /// </summary>
        internal static string HostDisconnected {
            get {
                return ResourceManager.GetString("HostDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host rejected the connection..
        /// </summary>
        internal static string HostRejectedConnection {
            get {
                return ResourceManager.GetString("HostRejectedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not enter the host&apos;s current scene.
        /// </summary>
        internal static string HostSceneLoadFailed {
            get {
                return ResourceManager.GetString("HostSceneLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolation delay.
        /// </summary>
        internal static string InterpolationDelay {
            get {
                return ResourceManager.GetString("InterpolationDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolation buffer for remote player movement, in seconds.
        /// </summary>
        internal static string InterpolationDelayTooltip {
            get {
                return ResourceManager.GetString("InterpolationDelayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client has no valid player ID..
        /// </summary>
        internal static string InvalidClientPlayerId {
            get {
                return ResourceManager.GetString("InvalidClientPlayerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid listen address: {0}.
        /// </summary>
        internal static string InvalidListenAddress {
            get {
                return ResourceManager.GetString("InvalidListenAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join address.
        /// </summary>
        internal static string JoinAddress {
            get {
                return ResourceManager.GetString("JoinAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Game.
        /// </summary>
        internal static string JoinGame {
            get {
                return ResourceManager.GetString("JoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host listen address.
        /// </summary>
        internal static string ListenAddress {
            get {
                return ResourceManager.GetString("ListenAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied the next time hosting starts.
        /// </summary>
        internal static string ListenAddressTooltip {
            get {
                return ResourceManager.GetString("ListenAddressTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer error: {0}.
        /// </summary>
        internal static string MultiplayerErrorFormat {
            get {
                return ResourceManager.GetString("MultiplayerErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer failed: {0}.
        /// </summary>
        internal static string MultiplayerFailedFormat {
            get {
                return ResourceManager.GetString("MultiplayerFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string NetworkGroup {
            get {
                return ResourceManager.GetString("NetworkGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No free space in the backpack.
        /// </summary>
        internal static string NoInventorySpace {
            get {
                return ResourceManager.GetString("NoInventorySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other player disconnected.
        /// </summary>
        internal static string OtherPlayerDisconnected {
            get {
                return ResourceManager.GetString("OtherPlayerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game already has two players..
        /// </summary>
        internal static string PartyFull {
            get {
                return ResourceManager.GetString("PartyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You died. Spectating the other player..
        /// </summary>
        internal static string PlayerDiedSpectating {
            get {
                return ResourceManager.GetString("PlayerDiedSpectating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string PlayerGroup {
            get {
                return ResourceManager.GetString("PlayerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} joined the game.
        /// </summary>
        internal static string PlayerJoinedFormat {
            get {
                return ResourceManager.GetString("PlayerJoinedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A player is joining....
        /// </summary>
        internal static string PlayerJoining {
            get {
                return ResourceManager.GetString("PlayerJoining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer name.
        /// </summary>
        internal static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name shown to other players in multiplayer.
        /// </summary>
        internal static string PlayerNameTooltip {
            get {
                return ResourceManager.GetString("PlayerNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol version mismatch (host {0}, client {1})..
        /// </summary>
        internal static string ProtocolVersionMismatch {
            get {
                return ResourceManager.GetString("ProtocolVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready. Waiting for the other player....
        /// </summary>
        internal static string ReadyWaiting {
            get {
                return ResourceManager.GetString("ReadyWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot join your own game using the same Steam account..
        /// </summary>
        internal static string SameSteamAccount {
            get {
                return ResourceManager.GetString("SameSteamAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State update rate.
        /// </summary>
        internal static string StateRate {
            get {
                return ResourceManager.GetString("StateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player state updates sent per second.
        /// </summary>
        internal static string StateRateTooltip {
            get {
                return ResourceManager.GetString("StateRateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the other player to choose a scene.
        /// </summary>
        internal static string WaitingForScene {
            get {
                return ResourceManager.GetString("WaitingForScene", resourceCulture);
            }
        }
    }
}
