<Project>
  <PropertyGroup>
    <DuckovPath>D:\Program Files (x86)\Steam\steamapps\common\Escape from Duckov</DuckovPath>
    <ManagedPath>$(DuckovPath)\Duckov_Data\Managed</ManagedPath>
    <ModSettingPath Condition="'$(ModSettingPath)' == ''">D:\Program Files (x86)\Steam\steamapps\workshop\content\3167020\3595729494</ModSettingPath>
  </PropertyGroup>
</Project>
